plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.kotlin apply false
}

tasks.register("clean", Delete) {
    delete(rootProject.layout.buildDirectory)
}

ext {
    applicationId = "com.hardbacknutter.sshd"
    applicationVersionCode = 14
    applicationVersionName = "1.8.0"

    toolChain = 21

    // Android 11 as minimum... there are far to many issues/differences dealing
    // with storage permissions if we try for Android 10 or lower
    // See https://developer.android.com/training/data-storage
    minSdkVersion = 30
    targetSdkVersion = 35
    compileSdkVersion = 35

    // https://developer.android.com/studio/projects/configure-agp-ndk
    ndk = "28.0.13004108"
    // don't forget to update CMakeLists.txt cmake_minimum_required
    cmakeVersion = "4.0.2"
}